AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless TODO API

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: dotnet8
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref TodoTable

Resources:
  # DynamoDB Table
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TodoTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Lambda Function
  TodoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TodoApiFunction
      Handler: todo-serverless::todo_serverless.LambdaEntryPoint::FunctionHandlerAsync
      CodeUri: ./src/ToDoApi/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        Configuration: Release

  # S3 Bucket för TODO App Frontend (Private)
  TodoAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'todo-app-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 Bucket Policy för TODO App (CloudFront OAC Access)
  TodoAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TodoAppBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${TodoAppBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${TodoAppDistribution}'

  # CloudFront Origin Access Control för TODO App
  TodoAppOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'todo-app-oac-${AWS::AccountId}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution för TODO App
  TodoAppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: TodoAppS3Origin
            DomainName: !GetAtt TodoAppBucket.RegionalDomainName
            OriginAccessControlId: !Ref TodoAppOAC
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: TodoAppS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  # S3 Bucket för Swagger UI (Private)
  SwaggerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'todo-swagger-ui-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 Bucket Policy för Swagger UI (CloudFront OAC Access)
  SwaggerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SwaggerBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub '${SwaggerBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${SwaggerDistribution}'

  # CloudFront Origin Access Control för Swagger UI
  SwaggerOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'swagger-ui-oac-${AWS::AccountId}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution för Swagger UI
  SwaggerDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: SwaggerS3Origin
            DomainName: !GetAtt SwaggerBucket.RegionalDomainName
            OriginAccessControlId: !Ref SwaggerOAC
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultCacheBehavior:
          TargetOriginId: SwaggerS3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

  TodoAppUrl:
    Description: "TODO App CloudFront URL"
    Value: !Sub "https://${TodoAppDistribution.DomainName}"

  TodoAppBucketName:
    Description: "TODO App S3 Bucket Name"
    Value: !Ref TodoAppBucket

  SwaggerUrl:
    Description: "Swagger UI CloudFront URL"
    Value: !Sub "https://${SwaggerDistribution.DomainName}"

  SwaggerBucketName:
    Description: "Swagger UI S3 Bucket Name"
    Value: !Ref SwaggerBucket

  TodoAppDistributionId:
    Description: "TODO App CloudFront Distribution ID"
    Value: !Ref TodoAppDistribution

  SwaggerDistributionId:
    Description: "Swagger UI CloudFront Distribution ID"
    Value: !Ref SwaggerDistribution