AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless TODO API

Globals:
  Function:
    Timeout: 60
    MemorySize: 512
    Runtime: dotnet8
    Environment:
      Variables:
        DYNAMODB_TABLE_NAME: !Ref TodoTable

Resources:
  # DynamoDB Table
  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TodoTable
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Lambda Function
  TodoApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TodoApiFunction
      Handler: todo-serverless::todo_serverless.LambdaEntryPoint::FunctionHandlerAsync
      CodeUri: ./src/ToDoApi/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TodoTable
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      BuildMethod: dotnet8
      BuildProperties:
        Configuration: Release

  # S3 Bucket för TODO App Frontend
  TodoAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'todo-app-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # S3 Bucket Policy för TODO App
  TodoAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TodoAppBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${TodoAppBucket.Arn}/*'

  # S3 Bucket för Swagger UI
  SwaggerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'todo-swagger-ui-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # S3 Bucket Policy för Swagger UI
  SwaggerBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SwaggerBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub '${SwaggerBucket.Arn}/*'

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

  TodoAppUrl:
    Description: "TODO App URL"
    Value: !GetAtt TodoAppBucket.WebsiteURL

  SwaggerUrl:
    Description: "Swagger UI URL"
    Value: !GetAtt SwaggerBucket.WebsiteURL